const constants = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',

    ADD_CARTLINE: 'ADD_CARTLINE',
    CHANGE_CARTLINE_QUANTITY: 'CHANGE_CARTLINE_QUANTITY',
    REMOVE_CARTLINE: 'REMOVE_CARTLINE'
}

export default constants;